version: '2.4'

services:
  web-service:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '3004:3004'

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
    dev-db-data:
